Text_SeismicTossTeach::
    .string "The secrets of space…\n"
    .string "The mysteries of earth…\p"
    .string "There are so many things about\n"
    .string "which we know so little.\p"
    .string "But that should spur us to study\n"
    .string "harder, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about Seismic Toss?\n"
    .string "Should I teach that to a Pokémon?$"

Text_SeismicTossDeclined::
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Seismic Toss?$"

Text_SeismicTossTaught::
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "Moon Stone, huh?\p"
    .string "What's so special about it?\n"
    .string "Looks like an ordinary rock to me.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "July 20, 1969!\p"
    .string "Humankind first set foot on the\n"
    .string "moon that day.\p"
    .string "I bought a color TV just so I\n"
    .string "could watch that news.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "This month, we're running a space\n"
    .string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "I want a Pikachu!\n"
    .string "It's so cute!\p"
    .string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Yeah, a Pikachu soon, I promise!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Space Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "A meteorite that fell on Mt. Moon.\n"
    .string "It is thought to be a Moon Stone.$"

Text_WaterGunTeach::
    .string "I'm watering this plant with\n"
    .string "Water Gun!\p"
    .string "Want me to teach one of\n"
    .string "your Pokémon Water Gun!$"

Text_WaterGunDeclined::
    .string "Okay! I'll keep watering\n"
    .string "this plant!$"

Text_WaterGunWhichMon::
    .string "Great! Which Pokémon\n"
    .string "should learn Water Gun?$"
//todo: Make this tutor repeatable by giving him something to drink
Text_WaterGunTaught::
    .string "Whew! Now I feel relieved.\n"
    .string "But I'm thirsty again…$"
