ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"

ViridianCity_School_Text_GetOneGymBadge::
    .string "Hello, young Trainer!\p"
    .string "It seems you have just begun\n"
    .string "your journey!\p"
    .string "If you want to become a better\n"
    .string "Trainer, you should take on the Gym\l"
    .string "Leaders and obtain their Badges.\p"
    .string "Please return once you have obtained\n"
    .string "at least one Badge for a reward.\p"
    .string "Until then, be sure to read what's\n"
    .string "on the blackboard carefully!$"

ViridianCity_School_Text_GotOneGymBadge::
    .string "I see you have a Gym Badge!\p"
    .string "As reward, please take this!$"

ViridianCity_School_Text_QuickClaw::
    .string "Give this Quick Claw one of your\n"
    .string "Pokémon to hold, and it might\l"
    .string "attack first no matter its Speed!$"

ViridianCity_School_Text_QuickClawAway::
    .string "{PLAYER} put the Quick Claw away in\n"
    .string "the Bag's Items Pocket.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Poké Balls are used to catch\n"
    .string "Pokémon.\p"
    .string "Up to six Pokémon can be carried\n"
    .string "in your party.\p"
    .string "People who raise and battle\n"
    .string "with Pokémon are called Trainers.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "A healthy Pokémon may be hard to\n"
    .string "catch, so weaken it first.\p"
    .string "Poison, burn, or cause another\n"
    .string "status problem to weaken it.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "Pokémon Trainers seek others to\n"
    .string "engage in Pokémon battles.\p"
    .string "To Trainers, the taste of victory\n"
    .string "is sweet, indeed.\p"
    .string "Battles are constantly waged at\n"
    .string "Pokémon Gyms everywhere.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "The ultimate goal for all Pokémon\n"
    .string "Trainers is simple.\p"
    .string "It is to defeat the top eight\n"
    .string "Pokémon Gym Leaders.\p"
    .string "Do so to earn the right to face…\p"
    .string "The Elite Four of the Pokémon\n"
    .string "League!$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "Girl: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists Pokémon\n"
    .string "Status problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A Pokémon can't attack if it's\n"
    .string "asleep.\p"
    .string "Pokémon will stay asleep even\n"
    .string "after battles.\p"
    .string "Use Awakening to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces Attack power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use Burn Heal to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a Pokémon's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an Antidote to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen Pokémon becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use Ice Heal to thaw out the\n"
    .string "suffering Pokémon.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces Speed and may\n"
    .string "prevent the Pokémon from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use Paralyze Heal for treatment.$"

