Route22_NorthEntrance_Text_CanIConfide::
    .string "Can I confide in you?$"

Route22_NorthEntrance_Text_Confide::
    .string "I once tried to sneak behind the\n"
    .string "gates. I barely made it to the\l"
    .string "second one before I was caught.\p"
    .string "It still is humiliating to remember,\n"
    .string "but thank you for taking the time\l"
    .string "to listen to me.\p"
    .string "Please take this TM.$"

Route22_NorthEntrance_Text_OfCourseNot::
    .string "Of course not.\n"
    .string "I'm a stranger, after all.$"

Route22_NorthEntrance_Text_ReceivedTM121FromGirl::
    .string "{PLAYER} received TM121\n"
    .string "from the girl.$"

Route22_NorthEntrance_Text_ExplainTM121::
    .string "TM121 is a move called Confide.\p"
    .string "It makes the opponent lose focus\n"
    .string "and weakens its special moves.$"

Route22_NorthEntrance_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"
