ViridianCity_House_Text_DoYouHaveSpearow::
    .string "You're working on a Pokédex?\n"
    .string "Have you caught a Spearow?\p"
    .string "If you catch a Spearow, would\n"
    .string "you show me its Pokédex entry?$"

ViridianCity_House_Text_YouHaveCaughtSpearow::
    .string "You've caught Spearow?\n"
    .string "Let me see the Pokédex entry!\p"
    .string "…\n"
    .string "…\p"
    .string "I see…\n"
    .string "Thank you so much!\p"
    .string "Take this, my fellow Spearow friend!$"

ViridianCity_House_Text_ItMakesFlyingTypeATtacksMorePowerful::
    .string "Give it a Pokémon to hold to make\n"
    .string "its Flying-type attacks more\l"
    .string "powerful!$"

ViridianCity_House_Text_SharpBeakAway::
    .string "{PLAYER} put the Sharp Beak away in\n"
    .string "the Bag's Items Pocket.$"

ViridianCity_House_Text_NicknamingIsFun::
    .string "Coming up with nicknames is fun,\n"
    .string "but it's not so easy to do.\p"
    .string "Clever names are nice, but simple\n"
    .string "names are easier to remember.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "My daddy loves Pokémon, too.$"

ViridianCity_House_Text_Speary::
    .string "Speary: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "Spearow\n"
    .string "Name: Speary$"

